version: 2.1

jobs:
  steps:
    - node/test:
        version: '18.7'
        pkg-manager: npm
    - run:
        name: Codecov Coverage 
        command: | 
          eslint 'src/**'
          npm run test:codecov

