version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  coverage_test:
    executor: 
      name: node/default
      tag: 18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Codecov Coverage 
          command: | 
            eslint 'src/**'
            npm run test:codecov
workflows:
  test_my_api:
    jobs:
      - coverage_test
