version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  coverage_test:
    docker: 
      - image: arkelaw/node:18
        auth:
            username: arkelaw
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - run:
          name: Remote Coverage 
          command: | 
            npm run test:codecov
      - coveralls/upload
workflows:
  test_my_api:
    jobs:
      - coverage_test
