version: 2.1

  jobs:
    - node/test:
        version: '18.7'
        pkg-manager: npm

    steps:
      - run:
          name: Codecov Coverage 
          command: | 
            eslint 'src/**'
            npm run test:codecov

