version: 2.1
jobs:
  coverage_test:
    docker: 
      - image: circleci/node:17
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - run:
          name: Codecov Coverage 
          command: | 
            npm run test:codecov
workflows:
  test_my_api:
    jobs:
      - coverage_test
